### ISSUE TITLE
Properly handle interleaved messages in Flowee

### ISSUE THREAD

**Issue by fstromback** [bitpal/bitpal#47]
The Flowee binary protocol allows for long messages to be split into chunks of 8KiB or so. We support this properly. The protocol does, however, allow for other messages to be transmitted in between these chunks. We don't handle that correctly at the moment as the code in Flowee doesn't seem to utilize this yet. We should be robust here, though.

For completeness we should perhaps also split outgoing messages to handle messages larger than 32KiB. Currently, we don't ever to this, so it is not a pressing issue.

This would, however, need some refactoring of the interface to Flowee.

**Comment by treeman** [comment]
Flowee is no longer up-to-date with BCH consensus rules, so closing this for now.
