### ISSUE TITLE
The Flowee backend never seems to unsubscribe from an address

### ISSUE THREAD

**Issue by fstromback** [bitpal/bitpal#48]
Now that we are generating new addresses for transactions, we need to consider unsubscribing from addresses when we no longer need to look at them.

**Comment by treeman** [comment]
This should be pretty easy to do. I'll take a look at it when I add more recovery logic if a process crashes somewhere.

As long as there's an "unsubscribe message" we've implemented?

**Comment by fstromback** [comment]
Yup, it is there waiting to be used :)

**Comment by fstromback** [comment]
To clarify, I don't feel this is pressing, but I wrote it down here to not forget.

**Comment by treeman** [comment]
> To clarify, I don't feel this is pressing, but I wrote it down here to not forget.

Totally, and I think that's the way to go with these issues.

**Comment by treeman** [comment]
Flowee is no longer up-to-date with BCH consensus rules, so closing this for now.
